# readthedocs.yml

version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
  apt_packages: 
    - cmake
    - make
    - libeigen3-dev
    - libboost-all-dev
  # jobs:
    # post_install:
    #   - wget https://github.com/openbabel/openbabel/releases/download/openbabel-3-1-1/openbabel-3.1.1-source.tar.bz2 
    #   - mkdir openbabel && tar xjvf openbabel-3.1.1-source.tar.bz2 -C openbabel
    #   - mkdir build
    #   - cd build && cmake ../openbabel
    #   - make -j4 && sudo make install
python:
  install:
    - method: pip
      path: .

conda:
  environment: docs/requirements.yaml
