#!/bin/env python

import pandas as pd
import numpy as np
import click
import os
from glob import glob
from plumbum.cmd import obabel

from utils import *

###############################################################################

# Defaults
stats_root = os.environ['COMBINDHOME']+'/stats_data/default'
mcss_version = 'mcss16'
shape_version = 'pharm_max'
ifp_version = 'rd1'

@click.group()
def main():
    pass

@main.command()
@click.argument('struct', default='')
@click.option('--templ-struct')
def structprep(struct, templ_struct):
    """
    Prepare structures and make a docking template file.

    "struct" specifies the name of the structure for which to make a docking
    template file. (Not the full path, generally just the PDB code.) Defaults to the
    structure with alphabetically lowest name.

    The following directory structure is required:

    \b
    structures/
        raw/
            structure_name.pdb
            structure_name.info (first line is Resname of ligand)
            ...
        processed/
            structure_name/structure_name_prot.pdb
            ...
        aligned/
            structure_name/structure_name_aligned.pdb
            ...
        proteins/
            structure_name_prot.pdb
            ...
        ligands/
            structure_name_lig.pdb
            ...
        template/
            structure_name/structure_name
            ...

    The process can be started from any step, e.g. if you have processed
    versions of your structures, you can place these in the processed directory.

    Files ending with _lig contain only the small molecule ligand present in the
    structure, and files ending with _prot contain everything else.
    """
    from dock.struct_align import struct_align
    from dock.struct_sort import struct_sort
    from dock.struct_process import struct_process
    from dock.grid import make_grid

    assert os.path.exists('structures'), 'No structures directory.'

    structs = sorted(glob('structures/raw/*.pdb*'))
    structs = [struct.split('/')[-1].split('.pdb')[0] for struct in structs]
    
    if not struct:
        struct = structs[0]

    if not templ_struct:
        templ_struct = struct

    print(f'Processing {structs}, aligning to {struct}, and creating a docking'
          f' templ for {templ_struct}')

    struct_process(structs)
    struct_align(struct, structs)
    struct_sort(structs)
    make_grid(templ_struct)

# Not super sure what is absolutely necessary in this step, especially if starting from sdf
# instead of starting from smiles
@main.command()
@click.argument('smiles')
@click.option('--root', default='ligands')
@click.option('--multiplex', is_flag=True)
@click.option('--sdffile', is_flag=True)
@click.option('--ligand-names', default='ID')
@click.option('--ligand-smiles', default='SMILES')
@click.option('--delim', default=',')
@click.option('--processes', default=1)
def ligprep(smiles, root, multiplex, ligand_names, ligand_smiles, delim, processes, sdffile):
    """
    Prepare ligands for docking, from smiles.

    Specifically, this will run Schrodinger's ligprep and then perform
    additional processing to make the ligands readable by rdkit and to assign
    atom names.

    "smiles" should be a `delim` delimited file with columns "ligand-names"
    and "ligand-smiles".
    
    "root" specifies where the processed ligands will be written. 

    By default, an individual file will be made for each ligand. If multiplex is
    set, then only one file, containing all the ligands, will be produced.

    Multiprocessing is only supported for non-multiplexed mode.
    """
    from dock.ligprep import ligprep, ligsplit
    mkdir(root)
    if not sdffile:
        ligands = pd.read_csv(smiles, sep=delim)
        print('Prepping {} mols from {} in {}'.format(len(ligands), smiles, root))
        if multiplex:
            _name = os.path.splitext(os.path.basename(smiles))[0]
            _root = f'{root}/{_name}'
            _smiles = f'{_root}/{_name}.smi'
            _sdf = os.path.splitext(_smiles)[0] + '.sdf'

            if not os.path.exists(_sdf):
                mkdir(_root)
                with open(_smiles, 'w') as fp:
                    for _, ligand in ligands.iterrows():
                        fp.write('{} {}\n'.format(ligand[ligand_smiles], ligand[ligand_names]))
                ligprep(_smiles)
        else:
            unfinished = []
            for _, ligand in ligands.iterrows():
                _name = ligand[ligand_names]
                _root = f'{root}/{_name}'
                _smiles = f'{_root}/{_name}.smi'
                _sdf = os.path.splitext(_smiles)[0] + '.sdf'

                if not os.path.exists(_sdf):
                    mkdir(_root)
                    with open(_smiles, 'w') as fp:
                        fp.write('{} {}\n'.format(ligand[ligand_smiles], ligand[ligand_names]))
                    unfinished += [(_smiles,)]
            mp(ligprep, unfinished, processes)
    else:
        ligsplit(smiles, root)

@main.command()
@click.argument('ligands', nargs=-1)
@click.option('--root', default='docking')
@click.option('--template')
@click.option('--screen', is_flag=True)
@click.option('--slurm', is_flag=True)
def dock(template, root, ligands, screen, slurm):
    """
    Dock "ligands" to "grid".

    "root" specifies where the docking results will be written.

    Setting "screen" limits the thoroughness of the pose sampling. Recommended
    for screening, but not pose prediction.

    "ligands" are paths to prepared ligand files. Multiple can be specified.
    """
    from dock.dock import dock

    if template is None:
        template = glob('structures/template/*.template')
        if template:
            template = template[0]
        else:
            print('No templates in default location (structures/template)'
                  ', please specify path.')
            exit()


    ligands = [os.path.abspath(lig) for lig in ligands if 'nonames' not in lig]
    template = os.path.abspath(template)
    root = os.path.abspath(root)

    mkdir(root)
    ligs = []
    _roots = []
    names = []
    for ligand in ligands:
        name = '{}-to-{}'.format(basename(ligand), basename(template))
        _root = '{}/{}'.format(root, name)
        ligs.append(ligand)
        _roots.append(_root)
        names.append(name)
    print(f"Writing docking file for {len(ligs)} ligands")
    dock(template, ligands, _roots, names, not screen, slurm=slurm)

################################################################################

@main.command()
@click.argument('root')
@click.argument('poseviewers', nargs=-1)
@click.option('--native', default='structures/ligands/*_lig.sdf')
@click.option('--ifp-version', default=ifp_version)
@click.option('--mcss-version', default=mcss_version)
@click.option('--shape-version', default=shape_version)
@click.option('--screen', is_flag=True)
@click.option('--max-poses', default=100)
@click.option('--no-mcss', is_flag=True)
@click.option('--use-shape', is_flag=True)
@click.option('--processes', default=1)
def featurize(root, poseviewers, native, ifp_version, mcss_version,
              shape_version, screen, no_mcss, use_shape, processes, max_poses):
    from features.features import Features
    if use_shape:
        print("Shape is not currently implemented outside of Schrodinger\n Shape has not been evaluated for performance in pose-prediction")

    native_poses = {}
    for native_path in glob(native):
        name = native_path.split('/')[-1].split('_lig')[0]
        # sts = Chem.SDMolSupplier(native_path)
        native_poses[name] = native_path

    features = Features(root, ifp_version=ifp_version, shape_version=shape_version,
                        mcss_version=mcss_version, max_poses=max_poses)

    features.compute_single_features(poseviewers, native_poses=native_poses)

    if screen:
        assert len(poseviewers) == 2
        features.compute_pair_features(poseviewers[:1],
                                       pvs2 = poseviewers[1:],
                                       mcss=not no_mcss, shape=use_shape)
    else:
        features.compute_pair_features(poseviewers,
                                       mcss=not no_mcss, shape=use_shape, processes=processes)

################################################################################

@main.command()
@click.argument('root')
@click.argument('out')
@click.argument('ligands', nargs=-1)
@click.option('--features', default='mcss,hbond,saltbridge,contact')
@click.option('--alpha', default=1.0)
@click.option('--stats-root', default=stats_root)
@click.option('--restart', default=500)
@click.option('--max-iterations', default=1000)
def pose_prediction(root, out, ligands, alpha, stats_root,
                    features, restart, max_iterations):
    """
    Run ComBind pose prediction.
    """
    from score.pose_prediction import PosePrediction
    from score.statistics import read_stats
    from features.features import Features

    features = features.split(',')

    protein = Features(root)
    protein.load_features()

    if not ligands:
        ligands = set(protein.raw['name1'])
    ligands = sorted(ligands)

    data = protein.get_view(ligands, features)
    stats = read_stats(stats_root, features)
    
    ps = PosePrediction(ligands, features, data, stats, alpha)
    best_poses = ps.max_posterior(max_iterations, restart)

    with open(out, 'w') as fp:
        fp.write('ID,POSE,COMBIND_RMSD,GNINA_RMSD,BEST_RMSD\n')
        for ligand in best_poses:
            rmsds = data['rmsd'][ligand]
            grmsd = rmsds[0]
            crmsd = rmsds[best_poses[ligand]]
            brmsd = min(rmsds)
            fp.write(','.join(map(str, [ligand.replace('_pv', ''),
                                        best_poses[ligand],
                                        crmsd, grmsd, brmsd]))+ '\n')

@main.command()
@click.argument('score-fname')
@click.argument('root')
@click.option('--stats-root', default=stats_root)
@click.option('--alpha', default=1.0)
@click.option('--features', default='shape,hbond,saltbridge,contact')
def screen(score_fname, root, stats_root, alpha, features):
    """
    Run ComBind screening.
    """
    from score.screen import screen, load_features_screen
    from score.statistics import read_stats

    features = features.split(',')
    stats = read_stats(stats_root, features)
    single, raw = load_features_screen(features, root)

    combind_energy = screen(single, raw, stats, alpha)
    np.save(score_fname, combind_energy)

################################################################################

@main.command()
@click.argument('scores')
@click.argument('original_pvs', nargs=-1)
def extract_top_poses(scores, original_pvs):
    """
    Write top-scoring poses to a single file.
    """
    out = scores.replace('.csv', '.sdf.gz')
    scores = pd.read_csv(scores).set_index('ID')

    writer = Chem.SDWriter(out)

    counts = {}
    written = []
    for pv in original_pvs:
        sts = Chem.ForwardSDMolSupplier(gzip.open(pv))
        for st in sts:
            name = st.GetProp("_Name")
            if name not in counts:
                counts[name] = 0
            else:
                # counts is zero indexed.
                counts[name] += 1

            if name in scores.index and scores.loc[name, 'POSE'] == counts[name]:
                writer.append(st)
                written += [name]

    assert len(written) == len(scores), written
    for name in scores.index:
        assert name in written

@main.command()
@click.argument('pv')
@click.argument('scores')
@click.argument('out', default=None)
def apply_scores(pv, scores, out):
    """
    Add ComBind screening scores to a poseviewer.
    """
    from score.screen import apply_scores
    if out is None:
        out = pv.replace('_pv.maegz', '_combind_pv.maegz')
    apply_scores(pv, scores, out)

@main.command()
@click.argument('pv')
@click.argument('out', default=None)
def scores_to_csv(pv, out):
    """
    Write docking and ComBind scores to text.
    """
    from score.screen import scores_to_csv
    scores_to_csv(pv, out)

main()
