name: docs
channels:
  - conda-forge
dependencies:
    # Base depends
  - python
  - pip
  - rdkit
  - pandas
  - numpy
  - pymol-open-source



    # Pip-only installs
  - pip:
    - ProDy>=2.0
    - click
    - plumbum
